export { AIService } from './ai/ai-service.ts'
export { AIAnalysisQueue } from './ai/analysis-queue.ts'
export type { AIAnalysisQueueOptions, AIAnalysisQueueResult } from './ai/analysis-queue.ts'
export { AIProviderError, classifyAIError, codeFromHttpStatus } from './ai/ai-errors.ts'
export type { AIProviderErrorCode } from './ai/ai-errors.ts'
export { buildAIRecoveryAdvice, listAIFailurePolicyPresets } from './ai/failure-policy.ts'
export type { AIRecoveryAdvice, AIFailurePolicyPreset } from './ai/failure-policy.ts'
export { OpenAICompatibleLLMClient, normalizeIntentResult } from './ai/llm-client.ts'
export type { LLMClient } from './ai/llm-client.ts'
export { estimateModelCostUsd, findModelPricing, listMergedModelPricing, listModelPricing, modelPricingTable, normalizeCustomPricing } from './ai/model-pricing.ts'
export type { ModelPricing, ModelPricingView } from './ai/model-pricing.ts'
export { buildIntentAnalysisPrompt } from './ai/prompt-templates.ts'
export { defaultBaseUrl, effectiveAIProviderBaseUrl, normalizeAIProviderBaseUrl } from './ai/provider-url.ts'
export { ApplicationCore, createDefaultApplicationCore } from './application/application-core.ts'
export type { PlatformLoginResult } from './application/application-core.ts'
export { BrowserContextManager } from './browser/browser-context-manager.ts'
export type { LoginWindowResult } from './browser/browser-context-manager.ts'
export { LeadMinerRepository } from './data/repository.ts'
export type * from './domain/types.ts'
export { contentRefFromManualImport, getManualImportTemplate, manualCommentFingerprint, manualCommentId, normalizeManualImportInput, parseCommentCsv } from './import/manual-import.ts'
export { MetadataOnlyPlatformAdapter } from './platform/adapter.ts'
export { canBatchCollectPlatform, canLoginPlatform, canSearchPlatform, hasPlatformCapability, isActivePlatform, requiresSingleItemCollection } from './platform/capability-policy.ts'
export { builtinPlatformSpecs, createBuiltinPlatformRegistry, platformExpansionTargetSpecs } from './platform/builtin.ts'
export { PlatformRegistry } from './platform/registry.ts'
export { OfficialApiError, OfficialApiPlatformAdapter } from './platform/official-api-adapter.ts'
export type { ApiFetch, OfficialApiErrorCode, PlatformConnectorConfigProvider, PlatformConnectorRuntimeConfig } from './platform/official-api-adapter.ts'
export { SearchEngineAdapter } from './platform/search-engine-adapter.ts'
export { VideoPlatformAdapter, buildBilibiliChildReplyUrl, buildBilibiliReplyUrl, calculateBilibiliRetryDelayMs, signBilibiliWbiParams } from './platform/video-platform-adapter.ts'
export { extractBilibiliAid, extractBilibiliApiError, extractBilibiliApiErrorInfo, extractBilibiliNextOffset, extractBilibiliReplyRoots, extractBilibiliWbiKeys, extractInstagramPageCursor, extractKuaishouPageCursor, extractRedditMoreChildren, extractShortVideoCursor, extractWeiboPageCursor, extractXiaohongshuPageCursor, extractYoutubeContinuationRequests, extractZhihuPageCursor, parseBilibiliComments, parseGenericHtmlComments, parseInstagramComments, parseKuaishouComments, parseRedditComments, parseShortVideoComments, parseWeiboComments, parseXiaohongshuComments, parseYoutubeComments, parseZhihuComments } from './platform/comment-parser.ts'
export type { BilibiliApiErrorInfo, BilibiliWbiKeys, XiaohongshuPageCursor, YoutubeContinuationRequest } from './platform/comment-parser.ts'
export { DisabledSearchPageExecutor, PlaywrightSearchPageExecutor, isAllowedPlatformFinalUrl, isAuthCookie, parseSearchResultHtml } from './platform/search-page-executor.ts'
export type { SearchPageExecutor } from './platform/search-page-executor.ts'
export { CompliancePolicy } from './policy/compliance-policy.ts'
export { PlainSecretCodec } from './security/secret-codec.ts'
export type { SecretCodec } from './security/secret-codec.ts'
export { TaskOrchestrator } from './task/task-orchestrator.ts'
